apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app  
  namespace: argocd  
spec:
  project: default  
  source:
    repoURL: https://github.com/vishalpatil0105/helm-charts  
    targetRevision: HEAD  
    path: python-application

  destination:
    server: https://kubernetes.default.svc  
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
